### ISSUE TITLE
HPE ILO4/5 login/logout work-around

### ISSUE THREAD

**Issue by SLoeuillet** [xlab-si/redfish-client-ruby#32]
HPE Gen8/9/10 (ILO4/5) do return X-Auth-Token and Location token as requested by the spec.
But they fail on the body side to return the created session in the body.

https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.6.1.pdf p111 "The JSON response body that contains a full representation of the newly created session object"

But from the spec, the client should be able to logout either by using the Location header, or the odata.id from the body :
https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.6.1.pdf p112 "This is accomplished by performing a DELETE
to the Session resource identified by the hyperlink returned in the Location header when the session was
created, or the 'sessionId' returned in the response data."

Current code does only look at odata.id from body :+1: 
```
    def session_login
      # We bypass do_request here because we do not want any retries on 401
      # when doing login.
      params = prepare_request_params(:post, @session_path,
                                      "UserName" => @username,
                                      "Password" => @password)
      r = @connection.request(params)
      raise_invalid_auth_error unless r.status == 201 

      token = r.data[:headers][TOKEN_AUTH_HEADER]
      add_headers(TOKEN_AUTH_HEADER => token)
      @session_oid = JSON.parse(r.data[:body])["@odata.id"]
    end
```

Could this be changed to use the Location header first and to look at the body if Location header is missing ?

2 samples :
Location: https://qlbovirt20001a-lc.devqa.exch.int/redfish/v1/SessionService/Sessions/admin5ca468b2f9667c52/

Location: https://mpdcsdbo01a-lc.oad.exch.int/redfish/v1/SessionService/Sessions/admin000000005ca49514ed13e809/

I did open a case with HPE on my side.
Of course, as you see, the Location header contains the full URL (including the hostname), not a relative one

Case opened on RedHat side with their CloudForms support : https://access.redhat.com/support/cases/#/case/02350103

Case opened on HPE side : 5337599867

**Comment by tadeboro** [comment]
Adding a vendor-specific workarounds to our client is really low on our list of priorities. Since we have no access to the systems with semi-broken Redfish implementations, your best chance of getting this workaround into the client is to prepare pull request that we will review.

Do note though that returning absolute URI in location header is another deviation from the Redfish standard that requires this to be a relative path. This makes implementing proper workaround even messier, since our client expects relative paths in vast majority of places.

/cc @gberginc @matejart

**Comment by SLoeuillet** [comment]
Hello,

I understand it is crappy to have to workaround bastard implementations.
I'll try to prepare a MR once I have it working locally

But my main objective is to have HPE fix their shit

Regards,

SLoeuillet

Le mer. 3 avr. 2019 à 19:45, Tadej Borovšak <notifications@github.com> a
écrit :

**Comment by agrare** [comment]
Hey @tadeboro !  So I fully admit to not reading the whole redfish spec, but looking at the most recent version (https://www.dmtf.org/sites/default/files/standards/documents/DSP0266_1.10.0.pdf)

In section "13.3.3.2. Session login" it sounds like HP iLO isn't conforming to the spec here:
> The response to the POST request to create a session shall include:
• X-Auth-Token header. Contains a session authentication token that the client can use in
subsequent requests.
• Location header. Contains a hyperlink to the new Session resource.
• JSON response body. Contains the full representation of the new Session resource.

Specifically they are not following the "Contains the full representation of the new Session resource" part

It also sounds like the redfish-client isn't conforming to the following:
> The client that sends the session login request should save the session authentication token from the XAuth-Token header and the contents of the Location header from the response of the login POST request.

Then in section "13.3.3.4. Session termination or logout":
> The session terminates through a DELETE request to the Session resource defined in either the Location header URI or the session ID in the response data.

Is that a fair summary?

If so I think we should hold HP to account for now following the spec.  We should also follow the spec on saving the Location header and using it to logout.  WDYT?

**Comment by tadeboro** [comment]
The difference between the backend and the client here is in the *shall* and *should*. Shall in the Redfish standard means "required", which in turn means that the backend is not compliant. Should mean "recommended", so our client is perfectly OK to not implement all of that stuff.

But as I said, I will (and actually already did) review the PR if someone prepares it.
